In [1]:
import tensorflow as tf 
from tensorflow.keras.models import load_model
import numpy as np
import pickle
import pandas as pd

In [5]:
## load the trained model,scalar pickle , onehpot
model = load_model('model.h5')

with open('onhot_encoder_geo.pkl','rb') as file:
    label_encoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scalar = pickle.load(file)

c:\Users\PRATHAM\OneDrive\Desktop\annclassification\venv\lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.5.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [43]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [44]:
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\PRATHAM\OneDrive\Desktop\annclassification\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [45]:
input_df = pd.DataFrame([input_data])
input_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [46]:
##Encode categorical varaibles        
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [47]:
##Concatination one hot encoded 
input_df = pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [48]:
#Scaling the input data
input_scaled =scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [49]:
##Pedict churn
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 25ms/step

array([[0.06929215, 0.06529315, 0.06904821, 0.11413363, 0.06933478,
        0.06974756, 0.06850196, 0.06654376, 0.0660378 , 0.0660084 ,
        0.06832869, 0.0599742 , 0.11762688, 0.06916492, 0.07399003,
        0.06854238]], dtype=float32)

In [52]:
prediction_proba = prediction[0][0]
prediction_proba

0.06929215

In [53]:
if(prediction_proba >= 0.5):
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.